/**
 * Brand build. Reads brand/tokens.json + the Bricolage Grotesque outlines and
 * emits every derived brand artefact:
 *
 *   src/styles/tokens.css        design tokens as CSS custom properties
 *   src/brand/geometry.ts        measured wordmark geometry for the React marks
 *   brand/assets/*.svg           locked lockups: primary, light, mono, icon
 *   public/favicon.svg           C-current glyph
 *   public/icon-512.svg          app icon
 *   public/manifest.webmanifest
 *
 * Run: npm run brand:build
 */

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildWordmark, buildGlyphMark, buildCurrentLineMotif } from './lib/wordmark.mts';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const FONT = join(here, 'fonts', 'BricolageGrotesque-SemiBold.ttf');

type Tokens = typeof import('./tokens.json');
const tokens: Tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const BANNER = `Generated by brand/build-assets.mts from brand/tokens.json — do not edit by hand.`;

function write(rel: string, body: string) {
  const abs = join(root, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, body);
  console.log(`  ✓ ${rel}  ${(body.length / 1024).toFixed(1)}kb`);
}

/* ────────────────────────────────────────────────────────────── gradients ── */

/**
 * Map a CSS gradient angle onto SVG linearGradient coordinates for a given box.
 * CSS angles run clockwise from "to top", so the direction vector in screen
 * space (y down) is (sin θ, −cos θ).
 */
function gradientCoords(angleDeg: number, box: { x: number; y: number; w: number; h: number }) {
  const rad = (angleDeg * Math.PI) / 180;
  const dx = Math.sin(rad);
  const dy = -Math.cos(rad);
  const len = Math.abs(box.w * dx) + Math.abs(box.h * dy);
  const cx = box.x + box.w / 2;
  const cy = box.y + box.h / 2;
  const r = (v: number) => Number(v.toFixed(2));
  return {
    x1: r(cx - (dx * len) / 2),
    y1: r(cy - (dy * len) / 2),
    x2: r(cx + (dx * len) / 2),
    y2: r(cy + (dy * len) / 2),
  };
}

function gradientDef(id: string, stops: string[], box: { x: number; y: number; w: number; h: number }) {
  const { x1, y1, x2, y2 } = gradientCoords(tokens.gradient.angle, box);
  const positions = tokens.gradient.positions;
  const inner = stops
    .map((c, i) => `      <stop offset="${(positions[i] * 100).toFixed(0)}%" stop-color="${c}"/>`)
    .join('\n');
  return `    <linearGradient id="${id}" gradientUnits="userSpaceOnUse" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}">
${inner}
    </linearGradient>`;
}

/* ──────────────────────────────────────────────────────────────── wordmark ── */

const wm = buildWordmark(FONT, tokens.typography.display.tracking);
const vb = `${wm.viewBox.x} ${wm.viewBox.y} ${wm.viewBox.w} ${wm.viewBox.h}`;

function wordmarkSvg(variant: 'primary' | 'light' | 'mono') {
  const stops = variant === 'light' ? tokens.gradient.onLight : tokens.gradient.onDark;
  const mono = variant === 'mono';
  const paint = mono ? 'currentColor' : `url(#water-${variant})`;
  const sparkPaint = mono ? 'currentColor' : tokens.color.spark.value;
  const color = mono ? ` color="${tokens.color.ink.value}"` : '';
  const id = `wm-${variant}`;

  // Opens a hairline of air where the climbing line crosses the n, so it reads
  // as passing behind the letterform. Mask space: white keeps, black cuts.
  const mask = `    <mask id="${id}-behind" maskUnits="userSpaceOnUse" x="${wm.viewBox.x}" y="${wm.viewBox.y}" width="${wm.viewBox.w}" height="${wm.viewBox.h}">
      <rect x="${wm.viewBox.x}" y="${wm.viewBox.y}" width="${wm.viewBox.w}" height="${wm.viewBox.h}" fill="#fff"/>
      <path d="${wm.knockout}" fill="#000" stroke="#000" stroke-width="${wm.knockoutWidth}" stroke-linejoin="round"/>
    </mask>`;
  const defs = mono
    ? `\n  <defs>\n${mask}\n  </defs>`
    : `\n  <defs>\n${gradientDef(`water-${variant}`, stops, wm.viewBox)}\n${mask}\n  </defs>`;

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}" width="${Math.round(wm.viewBox.w / 4)}" height="${Math.round(wm.viewBox.h / 4)}" role="img" aria-label="current"${color}>
  <title>current</title>
  <desc>${BANNER} Wordmark, ${variant}. The current line swells into the t-crossbar as one continuous form, and passes behind the n.</desc>${defs}
  <path d="${wm.currentLine}" fill="${paint}" mask="url(#${id}-behind)"/>
  <path d="${wm.letters}" fill="${paint}"/>
  <circle cx="${wm.spark.x}" cy="${wm.spark.y}" r="${wm.spark.r}" fill="${sparkPaint}"/>
</svg>
`;
}

/* ─────────────────────────────────────────────────────────── C-current mark ── */

const gm = buildGlyphMark(FONT);

/** Square icon canvas with the mark optically centred. */
function iconSvg(opts: { size: number; bg: string | null; withWave: boolean; stops: string[]; radius?: number }) {
  const { size, bg, withWave, stops } = opts;
  const box = { x: 0, y: 0, w: 100, h: 100 };
  // Fit the whole mark — letter plus wave plus spark when present — into the
  // canvas, so nothing ever overflows the icon.
  const fit = withWave ? gm.markBox : gm.letterBox;
  const inset = withWave ? 17 : 24;
  const avail = 100 - inset * 2;
  const lw = fit.right - fit.left;
  const lh = fit.bottom - fit.top;
  const scale = avail / Math.max(lw, lh);
  const tx = inset + (avail - lw * scale) / 2 - fit.left * scale;
  const ty = inset + (avail - lh * scale) / 2 - fit.top * scale;

  const radius = opts.radius ?? 24;
  const bgRect = bg
    ? `\n  <rect x="0" y="0" width="100" height="100" rx="${radius}" fill="${bg}"/>`
    : '';

  const wave = withWave
    ? `\n    <path d="${gm.wave}" fill="none" stroke="${tokens.color.spark.value}" stroke-width="${gm.strokeWidth}" stroke-linecap="round"/>
    <circle cx="${gm.spark.x}" cy="${gm.spark.y}" r="${gm.spark.r}" fill="${tokens.color.spark.value}"/>`
    : '';

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="${size}" height="${size}" role="img" aria-label="current">
  <title>current</title>
  <desc>${BANNER} C-current glyph${withWave ? '' : ' — wave dropped for use below the 24px floor'}.</desc>
  <defs>
${gradientDef('icon-water', stops, box)}
  </defs>${bgRect}
  <g transform="translate(${tx.toFixed(3)} ${ty.toFixed(3)}) scale(${scale.toFixed(5)})">
    <path d="${gm.letter}" fill="url(#icon-water)"/>${wave}
  </g>
</svg>
`;
}

/* ───────────────────────────────────────────────────── current-line motif ── */

const motif = buildCurrentLineMotif(4);

function motifSvg() {
  const box = motif.viewBox;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box.x} ${box.y} ${box.w} ${box.h}" width="400" height="80" preserveAspectRatio="none" role="img" aria-label="current line">
  <title>current line</title>
  <desc>${BANNER} Signature motif for dividers, progress bars and loading states.</desc>
  <defs>
${gradientDef('motif-water', tokens.gradient.onDark, box)}
  </defs>
  <path d="${motif.d}" fill="none" stroke="url(#motif-water)" stroke-width="3.2" stroke-linecap="round"/>
</svg>
`;
}

/* ──────────────────────────────────────────────────────────────── CSS vars ── */

function fluid(min: number, max: number) {
  if (min === max) return `${min}px`;
  const lo = 375;
  const hi = 1280;
  const slope = (max - min) / (hi - lo);
  const intercept = min - lo * slope;
  return `clamp(${min}px, ${intercept.toFixed(3)}px + ${(slope * 100).toFixed(4)}vw, ${max}px)`;
}

function tokensCss() {
  const c = tokens.color;
  const g = tokens.gradient;
  const grad = (stops: string[]) =>
    `linear-gradient(${g.angle}deg, ${stops.map((s, i) => `${s} ${(g.positions[i] * 100).toFixed(0)}%`).join(', ')})`;

  const colorVars = Object.entries(c)
    .map(([k, v]) => `  --c-${k.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)}: ${v.value}; /* ${v.role} */`)
    .join('\n');

  const spaceVars = Object.entries(tokens.space)
    .map(([k, v]) => `  --space-${k}: ${v}px;`)
    .join('\n');

  const radiusVars = Object.entries(tokens.radius)
    .map(([k, v]) => `  --radius-${k}: ${v === 999 ? '999px' : `${v}px`};`)
    .join('\n');

  const motionVars = Object.entries(tokens.motion)
    .map(([k, v]) => `  --motion-${k}: ${v};`)
    .join('\n');

  const typeVars = Object.entries(tokens.typography.scale)
    .map(([k, s]) => {
      const family = s.font === 'display' ? 'var(--font-display)' : 'var(--font-ui)';
      return `  --type-${k}-size: ${fluid(s.min, s.max)};
  --type-${k}-weight: ${s.weight};
  --type-${k}-tracking: ${s.tracking}em;
  --type-${k}-leading: ${s.leading};
  --type-${k}-family: ${family};`;
    })
    .join('\n');

  return `/* ${BANNER}
 * ${tokens.$meta.source}
 */

:root {
  /* ── Palette ─────────────────────────────────────────────────────────── */
${colorVars}

  /* ── The water gradient — carries the brand ──────────────────────────── */
  --gradient-water: ${grad(g.onDark)};
  --gradient-water-light: ${grad(g.onLight)};
  --gradient-angle: ${g.angle}deg;

  /* Individual stops, so inline SVG marks pick up the right gradient for the
     active theme without re-rendering. */
${g.onDark.map((c, i) => `  --wm-stop-${i + 1}: ${c};`).join('\n')}

  /* ── Type ────────────────────────────────────────────────────────────── */
  --font-display: ${tokens.typography.display.stack};
  --font-ui: ${tokens.typography.ui.stack};
  --display-tracking: ${tokens.typography.display.tracking}em;
${typeVars}

  /* ── Space ───────────────────────────────────────────────────────────── */
${spaceVars}

  /* ── Radius ──────────────────────────────────────────────────────────── */
${radiusVars}

  /* ── Motion ──────────────────────────────────────────────────────────── */
${motionVars}

  /* ── Semantic surfaces (dark is the primary mode) ────────────────────── */
  --bg: var(--c-abyss);
  --surface: var(--c-tide);
  --surface-raised: #103050;
  --text: var(--c-ink);
  --text-muted: color-mix(in oklab, var(--c-ink) 62%, var(--c-tide));
  --text-faint: color-mix(in oklab, var(--c-ink) 40%, var(--c-tide));
  --hairline: color-mix(in oklab, var(--c-river) 26%, transparent);
  --hairline-strong: color-mix(in oklab, var(--c-river) 46%, transparent);
  --gradient: var(--gradient-water);
  --scrim: linear-gradient(to top, var(--c-abyss) 8%, color-mix(in oklab, var(--c-abyss) 55%, transparent) 55%, transparent);
  --wordmark-clearspace: ${(wm.clearspace / wm.viewBox.h).toFixed(4)};
}

:root[data-theme='light'] {
  --bg: var(--c-foam);
  --surface: #ffffff;
  --surface-raised: #ffffff;
  --text: var(--c-ink-on-light);
  --text-muted: color-mix(in oklab, var(--c-ink-on-light) 68%, var(--c-foam));
  --text-faint: color-mix(in oklab, var(--c-ink-on-light) 46%, var(--c-foam));
  --hairline: color-mix(in oklab, var(--c-ink-on-light) 14%, transparent);
  --hairline-strong: color-mix(in oklab, var(--c-ink-on-light) 26%, transparent);
  --gradient: var(--gradient-water-light);
  --scrim: linear-gradient(to top, var(--c-foam) 8%, color-mix(in oklab, var(--c-foam) 55%, transparent) 55%, transparent);
${g.onLight.map((c, i) => `  --wm-stop-${i + 1}: ${c};`).join('\n')}
}
`;
}

/* ──────────────────────────────────────────────── generated TS geometry ── */

function geometryTs() {
  return `/* ${BANNER} */

export type MarkGeometry = {
  letters: string;
  knockout: string;
  knockoutWidth: number;
  currentLine: string;
  strokeWidth: number;
  spark: { x: number; y: number; r: number };
  viewBox: { x: number; y: number; w: number; h: number };
};

/** The wordmark. Current line and t-crossbar are one continuous stroke. */
export const wordmark = ${JSON.stringify({ letters: wm.letters, knockout: wm.knockout, knockoutWidth: wm.knockoutWidth, currentLine: wm.currentLine, strokeWidth: wm.strokeWidth, spark: wm.spark, viewBox: wm.viewBox }, null, 2)} as const;

/** Clearspace unit — the height of the "c" — as a fraction of the viewBox height. */
export const clearspaceRatio = ${(wm.clearspace / wm.viewBox.h).toFixed(4)};

/** The C-current glyph: favicon, app icon, avatar fallback, clip watermark. */
export const glyphMark = ${JSON.stringify(gm, null, 2)} as const;

/** Standalone current-line motif: dividers, progress bars, loading states. */
export const currentLineMotif = ${JSON.stringify(motif, null, 2)} as const;

/** Measured font metrics behind the lockup, kept for reference and tests. */
export const metrics = ${JSON.stringify(wm.metrics, null, 2)} as const;

/** Minimum sizes from the brand guide, in px. */
export const minSize = {
  wordmarkWidth: ${tokens.wordmark.minWidthPx},
  icon: ${tokens.wordmark.iconMinPx},
} as const;
`;
}

/* ───────────────────────────────────────────────────────────────── manifest ── */

function manifest() {
  return JSON.stringify(
    {
      name: 'current',
      short_name: 'current',
      description: 'A live platform for music creators and their fans.',
      start_url: '/',
      display: 'standalone',
      background_color: tokens.color.abyss.value,
      theme_color: tokens.color.abyss.value,
      icons: [
        { src: '/icon-512.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
        { src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
      ],
    },
    null,
    2,
  );
}

/* ────────────────────────────────────────────────────────────────── build ── */

console.log('\ncurrent · brand build');
console.log(`  wordmark ${wm.viewBox.w}×${wm.viewBox.h}  ·  line weight ${wm.strokeWidth}  ·  crossbar y ${wm.metrics.crossbar.centerY}`);
console.log(`  crossbar x ${wm.metrics.crossbar.left}→${wm.metrics.crossbar.right}  ·  line terminates at ${wm.metrics.crossbar.left} (coincident)\n`);

write('brand/assets/wordmark-primary.svg', wordmarkSvg('primary'));
write('brand/assets/wordmark-light.svg', wordmarkSvg('light'));
write('brand/assets/wordmark-mono.svg', wordmarkSvg('mono'));
write('brand/assets/icon.svg', iconSvg({ size: 512, bg: tokens.color.abyss.value, withWave: true, stops: tokens.gradient.onDark }));
write('brand/assets/icon-min.svg', iconSvg({ size: 24, bg: tokens.color.abyss.value, withWave: false, stops: tokens.gradient.onDark }));
write('brand/assets/current-line.svg', motifSvg());
write('public/icon-512.svg', iconSvg({ size: 512, bg: tokens.color.abyss.value, withWave: true, stops: tokens.gradient.onDark }));
write('public/favicon.svg', iconSvg({ size: 64, bg: tokens.color.abyss.value, withWave: true, stops: tokens.gradient.onDark, radius: 20 }));
write('public/manifest.webmanifest', manifest());
write('src/styles/tokens.css', tokensCss());
write('src/brand/geometry.ts', geometryTs());
write(
  'src/brand/tokens.ts',
  `/* ${BANNER} */\n\nexport const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`,
);

console.log('\n  brand build complete\n');
